In [1]:
#installing spark
!pip install spark

Requirement already satisfied: spark in c:\users\amanka5\anaconda3\lib\site-packages (0.2.1)

In [2]:
#installing pyspark 

!pip install pyspark
!pip install findspark

Requirement already satisfied: pyspark in c:\users\amanka5\anaconda3\lib\site-packages (3.3.0)
Requirement already satisfied: py4j==0.10.9.5 in c:\users\amanka5\anaconda3\lib\site-packages (from pyspark) (0.10.9.5)
Requirement already satisfied: findspark in c:\users\amanka5\anaconda3\lib\site-packages (2.0.1)

In [3]:
#importing spark
from pyspark.shell import spark

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.3.0
      /_/

Using Python version 3.9.12 (main, Apr  4 2022 05:22:27)
Spark context Web UI available at http://TS-STUDENT-5016.hsd1.il.comcast.net:4043
Spark context available as 'sc' (master = local[*], app id = local-1666589143471).
SparkSession available as 'spark'.

In [4]:
#importing pyspark and pandas
import pyspark
import pandas as pd

In [5]:
# Installing findspark - a python library to find Spark
!pip install -q findspark

In [6]:
##Loading spark session
from pyspark.context import SparkContext
from pyspark.sql.session import SparkSession
from pyspark.sql import SparkSession 
from pyspark.sql import SparkSession
from pyspark import SparkContext
from pyspark.sql import SQLContext

In [7]:
import os
os.environ["JAVA_HOME"] = "C:/Program Files/Java/jdk1.8.0_341-amd64"
os.environ["SPARK_HOME"] = "C:/Users/amanka5/Spark/spark-3.3.0-bin-hadoop2"

In [8]:
#read the Amazon_Responded_Oct05 dataset in csv
df = pd.read_csv("C:/Users/amanka5/Desktop/Amazondata.csv", on_bad_lines='skip')

In [9]:
df.head()

,id_str,tweet_created_at,user_screen_name,user_id_str,user_statuses_count,user_favourites_count,user_protected,user_listed_count,user_following,user_description,...,tweet_language,text_,favorite_count,favorited,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,retweet_count,retweeted,text
0,'793270689780203520',Tue Nov 01 01:57:25 +0000 2016,SeanEPanjab,143515471.0,51287,4079,False,74,False,Content marketer; Polyglot; Beard aficionado; ...,...,en,@AmazonHelp Can you please DM me? A product I ...,0,False,AmazonHelp,NaN,85741735.0,0,False,NaN
1,'793281386912354304',Tue Nov 01 02:39:55 +0000 2016,AmazonHelp,85741735.0,2225450,11366,False,796,False,We answer Amazon support questions 7 days a we...,...,en,"@SeanEPanjab I'm sorry, we're unable to DM you...",0,False,SeanEPanjab,7.932707e+17,143515471.0,0,False,NaN
2,'793501578766319616',Tue Nov 01 17:14:53 +0000 2016,SeanEPanjab,143515471.0,51287,4079,False,74,False,Content marketer; Polyglot; Beard aficionado; ...,...,en,@AmazonHelp It was purchased on https://t.co/g...,0,False,AmazonHelp,7.932814e+17,85741735.0,0,False,@AmazonHelp It was purchased on https://t.co/g...
3,'793501657346682880',Tue Nov 01 17:15:12 +0000 2016,SeanEPanjab,143515471.0,51287,4079,False,74,False,Content marketer; Polyglot; Beard aficionado; ...,...,en,"@AmazonHelp I am following you now, if it help...",0,False,AmazonHelp,7.932814e+17,85741735.0,0,False,NaN
4,'793502854459879424',Tue Nov 01 17:19:57 +0000 2016,AmazonHelp,85741735.0,2225450,11366,False,796,False,We answer Amazon support questions 7 days a we...,...,en,@SeanEPanjab Please give us a call/chat so we ...,0,False,SeanEPanjab,7.935016e+17,143515471.0,0,False,@SeanEPanjab Please give us a call/chat so we ...

In [10]:
#check column
df.columns

Index(['id_str', 'tweet_created_at', 'user_screen_name', 'user_id_str',
       'user_statuses_count', 'user_favourites_count', 'user_protected',
       'user_listed_count', 'user_following', 'user_description',
       'user_location', 'user_verified', 'user_followers_count',
       'user_friends_count', 'user_created_at', 'tweet_language', 'text_',
       'favorite_count', 'favorited', 'in_reply_to_screen_name',
       'in_reply_to_status_id_str', 'in_reply_to_user_id_str', 'retweet_count',
       'retweeted', 'text'],
      dtype='object')

In [11]:
#check the datatypes of column
df.dtypes

id_str                        object
tweet_created_at              object
user_screen_name              object
user_id_str                  float64
user_statuses_count            int64
user_favourites_count          int64
user_protected                  bool
user_listed_count              int64
user_following                  bool
user_description              object
user_location                 object
user_verified                   bool
user_followers_count           int64
user_friends_count             int64
user_created_at               object
tweet_language                object
text_                         object
favorite_count                 int64
favorited                       bool
in_reply_to_screen_name       object
in_reply_to_status_id_str    float64
in_reply_to_user_id_str      float64
retweet_count                  int64
retweeted                       bool
text                          object
dtype: object

In [12]:
df.shape

(378132, 25)

In [13]:
df.columns

Index(['id_str', 'tweet_created_at', 'user_screen_name', 'user_id_str',
       'user_statuses_count', 'user_favourites_count', 'user_protected',
       'user_listed_count', 'user_following', 'user_description',
       'user_location', 'user_verified', 'user_followers_count',
       'user_friends_count', 'user_created_at', 'tweet_language', 'text_',
       'favorite_count', 'favorited', 'in_reply_to_screen_name',
       'in_reply_to_status_id_str', 'in_reply_to_user_id_str', 'retweet_count',
       'retweeted', 'text'],
      dtype='object')

# Task 1


# Step 1: Remove the records where “user_verified” is “FALSE”

In [14]:
#considering only TRUE variables
df1 = df[df['user_verified'] == True]

In [15]:
df1['user_verified']

1         True
4         True
5         True
8         True
10        True
          ...
378122    True
378124    True
378127    True
378129    True
378131    True
Name: user_verified, Length: 171898, dtype: bool

In [16]:
df1['user_verified'].count()

171898

# Step 2: For the remaining records (“user_verified” is “TRUE”), group by created date, and count the number of tweets for each date.

In [17]:
df1.dtypes

id_str                        object
tweet_created_at              object
user_screen_name              object
user_id_str                  float64
user_statuses_count            int64
user_favourites_count          int64
user_protected                  bool
user_listed_count              int64
user_following                  bool
user_description              object
user_location                 object
user_verified                   bool
user_followers_count           int64
user_friends_count             int64
user_created_at               object
tweet_language                object
text_                         object
favorite_count                 int64
favorited                       bool
in_reply_to_screen_name       object
in_reply_to_status_id_str    float64
in_reply_to_user_id_str      float64
retweet_count                  int64
retweeted                       bool
text                          object
dtype: object

In [18]:
#checking the tweet_created_at column
df1.tweet_created_at

1         Tue Nov 01 02:39:55 +0000 2016
4         Tue Nov 01 17:19:57 +0000 2016
5         Tue Nov 01 17:25:26 +0000 2016
8         Tue Nov 01 18:02:03 +0000 2016
10        Tue Nov 01 03:59:02 +0000 2016
                       ...
378122    Wed Aug 02 00:04:31 +0000 2017
378124    Tue Aug 01 23:53:52 +0000 2017
378127    Tue Aug 01 23:59:28 +0000 2017
378129    Tue Aug 01 23:51:30 +0000 2017
378131    Wed Aug 02 02:00:00 +0000 2017
Name: tweet_created_at, Length: 171898, dtype: object

In [19]:
#converting the tweet_created_at into datetime
df1['tweet_created_at'] = pd.to_datetime(df1['tweet_created_at'], errors='coerce')

C:\Users\amanka5\AppData\Local\Temp\ipykernel_26096\727719884.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['tweet_created_at'] = pd.to_datetime(df1['tweet_created_at'], errors='coerce')

In [20]:
df1['tweet_created_at'].dt.day_name()

1           Tuesday
4           Tuesday
5           Tuesday
8           Tuesday
10          Tuesday
            ...
378122    Wednesday
378124      Tuesday
378127      Tuesday
378129      Tuesday
378131    Wednesday
Name: tweet_created_at, Length: 171898, dtype: object

In [21]:
#extracting the month and day from 'tweet_created_at' column 

df1['tweet_created_at']=df1['tweet_created_at'].apply(lambda x:x.ctime().split(' '))
df1['tweet_created_at']=df1['tweet_created_at'].apply(lambda x:' '.join([x[1],x[3]]))

C:\Users\amanka5\AppData\Local\Temp\ipykernel_26096\2755368625.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['tweet_created_at']=df1['tweet_created_at'].apply(lambda x:x.ctime().split(' '))
C:\Users\amanka5\AppData\Local\Temp\ipykernel_26096\2755368625.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['tweet_created_at']=df1['tweet_created_at'].apply(lambda x:' '.join([x[1],x[3]]))

In [22]:
dates = df1['tweet_created_at']

In [23]:
print(dates)

1         Nov 1
4         Nov 1
5         Nov 1
8         Nov 1
10        Nov 1
          ...
378122    Aug 2
378124    Aug 1
378127    Aug 1
378129    Aug 1
378131    Aug 2
Name: tweet_created_at, Length: 171898, dtype: object

In [24]:
import string 
import re 
import warnings
warnings.filterwarnings('ignore')

In [25]:
#getting the number of tweets by using groupby function

num_of_tweets = df1.groupby(['tweet_created_at']).size().reset_index(name='counts')

In [26]:
print(num_of_tweets)

      tweet_created_at  counts
0         Apr 00:00:00       2
1         Apr 00:00:03       1
2         Apr 00:00:26       1
3         Apr 00:00:31       1
4         Apr 00:00:32       1
...                ...     ...
74083            Nov 5    1058
74084            Nov 6     357
74085            Nov 7     592
74086            Nov 8     519
74087            Nov 9     231

[74088 rows x 2 columns]

In [27]:
df1.sort_values('tweet_created_at', ascending=False).head(10)

,id_str,tweet_created_at,user_screen_name,user_id_str,user_statuses_count,user_favourites_count,user_protected,user_listed_count,user_following,user_description,...,tweet_language,text_,favorite_count,favorited,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,retweet_count,retweeted,text
10630,'796486899347193856',Nov 9,AmazonHelp,85741735.0,2225790,11368,False,797,False,We answer Amazon support questions 7 days a we...,...,en,@SloaneEsq Please reach us via phone or chat a...,0,False,SloaneEsq,7.964857e+17,6.798862e+06,0,False,@SloaneEsq Please reach us via phone or chat a...
9591,'796141390321373192',Nov 9,AmazonHelp,85741735.0,2225779,11368,False,797,False,We answer Amazon support questions 7 days a we...,...,en,@Desi_tamancha by the said press release of th...,0,False,Desi_tamancha,7.960326e+17,3.875058e+08,0,False,NaN
10395,'796437958186455040',Nov 9,AmazonHelp,85741735.0,2225858,11367,False,792,False,We answer Amazon support questions 7 days a we...,...,en,@dilbil143 Please don't provide your tracking#...,0,False,dilbil143,7.963863e+17,1.272525e+09,0,False,NaN
7812,'796297417033453569',Nov 9,AmazonHelp,85741735.0,2225738,11368,False,792,False,We answer Amazon support questions 7 days a we...,...,en,@mcurie You guessed it right! Here is another ...,1,False,mcurie,7.962683e+17,1.447249e+07,0,False,@mcurie You guessed it right! Here is another ...
7810,'796261417368293376',Nov 9,AmazonHelp,85741735.0,2225738,11368,False,792,False,We answer Amazon support questions 7 days a we...,...,en,@mcurie Beautifully done *claps*. Our new deli...,1,False,mcurie,7.956782e+17,1.447249e+07,0,False,@mcurie Beautifully done *claps*. Our new deli...
10394,'796437659061256210',Nov 9,AmazonHelp,85741735.0,2225858,11367,False,792,False,We answer Amazon support questions 7 days a we...,...,en,"@dilbil143 Hi, sorry for the trouble you're ha...",0,False,dilbil143,7.963854e+17,1.272525e+09,0,False,"@dilbil143 Hi, sorry for the trouble you're ha..."
10389,'796498476901273600',Nov 9,AmazonHelp,85741735.0,2225786,11368,False,797,False,We answer Amazon support questions 7 days a we...,...,en,@onedurr Please contact us here: https://t.co/...,1,False,onedurr,7.964974e+17,2.724701e+07,0,False,@onedurr Please contact us here: https://t.co/...
10387,'796388492653854720',Nov 9,AmazonHelp,85741735.0,2225786,11368,False,797,False,We answer Amazon support questions 7 days a we...,...,en,@onedurr The first step you need to take is: h...,0,False,onedurr,7.963826e+17,2.724701e+07,0,False,@onedurr The first step you need to take is: h...
10385,'796372937980968960',Nov 9,AmazonHelp,85741735.0,2225795,11368,False,797,False,We answer Amazon support questions 7 days a we...,...,en,@PetrescuCosmin1 I'm sorry for the wait! Is it...,0,False,PetrescuCosmin1,7.963702e+17,3.523578e+09,0,False,@PetrescuCosmin1 I'm sorry for the wait! Is it...
10378,'796502068915830786',Nov 9,AmazonHelp,85741735.0,2225785,11368,False,797,False,We answer Amazon support questions 7 days a we...,...,en,@gtabassum I'm sorry for the inconvenience. Pl...,0,False,gtabassum,7.964030e+17,6.141606e+07,0,False,@gtabassum I'm sorry for the inconvenience. Pl...

In [28]:
#finding the day which has the highest number of tweet 


df1['tweet_created_at'].value_counts().head(5)

Jan 3    1536
Jan 6    1364
Jan 7    1360
Mar 2    1298
Dec 3    1201
Name: tweet_created_at, dtype: int64

In [29]:
sum_column = df1.loc[df1['tweet_created_at'] == 'Jan 3']

In [30]:
sum_column

,id_str,tweet_created_at,user_screen_name,user_id_str,user_statuses_count,user_favourites_count,user_protected,user_listed_count,user_following,user_description,...,tweet_language,text_,favorite_count,favorited,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,retweet_count,retweeted,text
66462,'816139627270721537',Jan 3,AmazonHelp,85741735.0,2192489,11066,False,792,False,We answer Amazon support questions 7 days a we...,...,en,@mcp111 Hey! We'll have this looked into inter...,0,False,mcp111,8.161344e+17,1.517868e+07,0,False,NaN
66464,'816357712732819467',Jan 3,AmazonHelp,85741735.0,2192489,11066,False,792,False,We answer Amazon support questions 7 days a we...,...,en,"@mcp111 Hi there, you can change the country f...",0,False,mcp111,8.163478e+17,1.517868e+07,0,False,NaN
66811,'816167583263162369',Jan 3,AmazonHelp,85741735.0,2193362,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,en,"@stevebrowne Hi Steve, sorry to hear this. As ...",0,False,stevebrowne,8.161666e+17,6.672772e+06,0,False,"@stevebrowne Hi Steve, sorry to hear this. As ..."
66943,'816326113660174336',Jan 3,AmazonHelp,85741735.0,2192505,11066,False,793,False,We answer Amazon support questions 7 days a we...,...,en,@boozysmurf We'd like the chance to look into ...,0,False,boozysmurf,8.163219e+17,1.675239e+07,0,False,@boozysmurf We'd like the chance to look into ...
67453,'816359349358575616',Jan 3,AmazonHelp,85741735.0,2192463,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,en,@MeghanSuslak If you have the tracking ID from...,0,False,MeghanSuslak,8.163582e+17,2.284562e+08,0,False,@MeghanSuslak If you have the tracking ID from...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78198,'816433714473402369',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,en,@jillkluke If it doesn't arrive tomorrow by 8p...,0,False,jillkluke,8.164330e+17,5.244206e+07,0,False,@jillkluke If it doesn't arrive tomorrow by 8p...
78200,'816431448928514049',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,en,@AriannaDelBene Hi- Thanks so much for bringin...,1,False,AriannaDelBene,8.164299e+17,2.153521e+09,0,False,NaN
78202,'816430945679147008',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,en,@TwinPines85 I'm sorry but not all orders are ...,0,False,TwinPines85,8.164301e+17,4.343482e+07,0,False,@TwinPines85 I'm sorry but not all orders are ...
78204,'816432570300764160',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,en,@_BrianMahoney I apologize for the delay. If y...,0,False,_BrianMahoney,8.164308e+17,2.573027e+07,0,False,@_BrianMahoney I apologize for the delay. If y...
78206,'816432057274552320',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,en,@12th__Fan Sorry they've been late. Have you c...,0,False,12th__Fan,8.164310e+17,2.896091e+08,0,False,@12th__Fan Sorry they've been late. Have you c...

# STEP 3 calculate the sum of “favorite_count” and “retweet_count” for each tweet on that day

In [31]:
#sum the favorite_count and retweet_count column

sum_column['sum_count'] = sum_column['favorite_count'] + sum_column['retweet_count']

In [32]:
sum_column

,id_str,tweet_created_at,user_screen_name,user_id_str,user_statuses_count,user_favourites_count,user_protected,user_listed_count,user_following,user_description,...,text_,favorite_count,favorited,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,retweet_count,retweeted,text,sum_count
66462,'816139627270721537',Jan 3,AmazonHelp,85741735.0,2192489,11066,False,792,False,We answer Amazon support questions 7 days a we...,...,@mcp111 Hey! We'll have this looked into inter...,0,False,mcp111,8.161344e+17,1.517868e+07,0,False,NaN,0
66464,'816357712732819467',Jan 3,AmazonHelp,85741735.0,2192489,11066,False,792,False,We answer Amazon support questions 7 days a we...,...,"@mcp111 Hi there, you can change the country f...",0,False,mcp111,8.163478e+17,1.517868e+07,0,False,NaN,0
66811,'816167583263162369',Jan 3,AmazonHelp,85741735.0,2193362,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,"@stevebrowne Hi Steve, sorry to hear this. As ...",0,False,stevebrowne,8.161666e+17,6.672772e+06,0,False,"@stevebrowne Hi Steve, sorry to hear this. As ...",0
66943,'816326113660174336',Jan 3,AmazonHelp,85741735.0,2192505,11066,False,793,False,We answer Amazon support questions 7 days a we...,...,@boozysmurf We'd like the chance to look into ...,0,False,boozysmurf,8.163219e+17,1.675239e+07,0,False,@boozysmurf We'd like the chance to look into ...,0
67453,'816359349358575616',Jan 3,AmazonHelp,85741735.0,2192463,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,@MeghanSuslak If you have the tracking ID from...,0,False,MeghanSuslak,8.163582e+17,2.284562e+08,0,False,@MeghanSuslak If you have the tracking ID from...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78198,'816433714473402369',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,@jillkluke If it doesn't arrive tomorrow by 8p...,0,False,jillkluke,8.164330e+17,5.244206e+07,0,False,@jillkluke If it doesn't arrive tomorrow by 8p...,0
78200,'816431448928514049',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,@AriannaDelBene Hi- Thanks so much for bringin...,1,False,AriannaDelBene,8.164299e+17,2.153521e+09,0,False,NaN,1
78202,'816430945679147008',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,@TwinPines85 I'm sorry but not all orders are ...,0,False,TwinPines85,8.164301e+17,4.343482e+07,0,False,@TwinPines85 I'm sorry but not all orders are ...,0
78204,'816432570300764160',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,@_BrianMahoney I apologize for the delay. If y...,0,False,_BrianMahoney,8.164308e+17,2.573027e+07,0,False,@_BrianMahoney I apologize for the delay. If y...,0
78206,'816432057274552320',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,@12th__Fan Sorry they've been late. Have you c...,0,False,12th__Fan,8.164310e+17,2.896091e+08,0,False,@12th__Fan Sorry they've been late. Have you c...,0

In [33]:
#getting the highest sum count

total_sum = sum_column.sort_values(by = 'sum_count', ascending=False)

In [34]:
total_sum

,id_str,tweet_created_at,user_screen_name,user_id_str,user_statuses_count,user_favourites_count,user_protected,user_listed_count,user_following,user_description,...,text_,favorite_count,favorited,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,retweet_count,retweeted,text,sum_count
77040,'816329761530093568',Jan 3,bhagyashree123,116392212.0,6683,230,False,322,False,"actress, mother, health enthusiast, travel jun...",...,"@amazon worst shopping experience, no servic...",4,False,amazon,NaN,2.079382e+07,1,False,NaN,5
74929,'816083406962434048',Jan 3,AmazonHelp,85741735.0,2193379,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,@ItsJosshA We always aim to deliver by the dat...,2,False,ItsJosshA,8.160816e+17,2.573227e+09,1,False,NaN,3
75021,'816095108013654017',Jan 3,AmazonHelp,85741735.0,2193377,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,@KStefl Sounds like you know what to add to yo...,1,False,KStefl,8.160924e+17,3.008914e+08,1,False,NaN,2
76792,'816314295680110593',Jan 3,AmazonHelp,85741735.0,2193308,11081,False,790,False,We answer Amazon support questions 7 days a we...,...,@thedexterouz Hi! We'd like to help. When you ...,2,False,thedexterouz,8.163107e+17,9.716845e+07,0,False,@thedexterouz Hi! We'd like to help. When you ...,2
75137,'816109446069911554',Jan 3,AmazonHelp,85741735.0,2193376,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,"@Schoey1992 Happy Birthday, Matt! #FriendsFore...",1,False,Schoey1992,8.161048e+17,4.069085e+08,1,False,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75826,'816220916560625664',Jan 3,AmazonHelp,85741735.0,2193351,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,"@wasimbinpeer Hi, although we try to resolve a...",0,False,wasimbinpeer,8.162168e+17,6.254646e+08,0,False,NaN,0
75824,'816216656192094208',Jan 3,AmazonHelp,85741735.0,2193351,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,"@wasimbinpeer Hi, in this case request you to ...",0,False,wasimbinpeer,8.162147e+17,6.254646e+08,0,False,NaN,0
75822,'816212738963865601',Jan 3,AmazonHelp,85741735.0,2193351,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,@wasimbinpeer assist you with the issue. 2/2 ^SH,0,False,wasimbinpeer,8.162078e+17,6.254646e+08,0,False,NaN,0
75821,'816212738561208320',Jan 3,AmazonHelp,85741735.0,2193351,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,"@wasimbinpeer Hi, as said earlier please reply...",0,False,wasimbinpeer,8.162078e+17,6.254646e+08,0,False,NaN,0
78206,'816432057274552320',Jan 3,AmazonHelp,85741735.0,2192454,11066,False,790,False,We answer Amazon support questions 7 days a we...,...,@12th__Fan Sorry they've been late. Have you c...,0,False,12th__Fan,8.164310e+17,2.896091e+08,0,False,@12th__Fan Sorry they've been late. Have you c...,0

# Calculating the top 100 tweets

In [35]:
#checking the 'text_' column

data = total_sum.nlargest(100, 'sum_count')

In [36]:
data

,id_str,tweet_created_at,user_screen_name,user_id_str,user_statuses_count,user_favourites_count,user_protected,user_listed_count,user_following,user_description,...,text_,favorite_count,favorited,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,retweet_count,retweeted,text,sum_count
77040,'816329761530093568',Jan 3,bhagyashree123,116392212.0,6683,230,False,322,False,"actress, mother, health enthusiast, travel jun...",...,"@amazon worst shopping experience, no servic...",4,False,amazon,NaN,2.079382e+07,1,False,NaN,5
74929,'816083406962434048',Jan 3,AmazonHelp,85741735.0,2193379,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,@ItsJosshA We always aim to deliver by the dat...,2,False,ItsJosshA,8.160816e+17,2.573227e+09,1,False,NaN,3
75021,'816095108013654017',Jan 3,AmazonHelp,85741735.0,2193377,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,@KStefl Sounds like you know what to add to yo...,1,False,KStefl,8.160924e+17,3.008914e+08,1,False,NaN,2
76792,'816314295680110593',Jan 3,AmazonHelp,85741735.0,2193308,11081,False,790,False,We answer Amazon support questions 7 days a we...,...,@thedexterouz Hi! We'd like to help. When you ...,2,False,thedexterouz,8.163107e+17,9.716845e+07,0,False,@thedexterouz Hi! We'd like to help. When you ...,2
75137,'816109446069911554',Jan 3,AmazonHelp,85741735.0,2193376,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,"@Schoey1992 Happy Birthday, Matt! #FriendsFore...",1,False,Schoey1992,8.161048e+17,4.069085e+08,1,False,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75548,'816163919597338625',Jan 3,AmazonHelp,85741735.0,2193364,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,"@QueenAttallah If you're waiting on an order, ...",1,False,QueenAttallah,8.161551e+17,7.316979e+17,0,False,"@QueenAttallah If you're waiting on an order, ...",1
75225,'816119611733188608',Jan 3,AmazonHelp,85741735.0,2193372,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,"@AthenaRivera4 Feel better soon, Athena! We'd ...",1,False,AthenaRivera4,8.161145e+17,2.251318e+09,0,False,NaN,1
76025,'816236161882607620',Jan 3,AmazonHelp,85741735.0,2193345,11081,False,792,False,We answer Amazon support questions 7 days a we...,...,@AbhinavSaroj3 features and customer experienc...,1,False,AbhinavSaroj3,8.162343e+17,7.657587e+17,0,False,@AbhinavSaroj3 features and customer experienc...,1
76014,'816231065949847552',Jan 3,singhvarun,47325599.0,26934,4064,False,32,False,"Assistant Editor, MA in Politics, LLB, Journal...",...,Thanks @amazonIN for delivering me a receiver ...,1,False,NaN,NaN,NaN,0,False,Thanks @amazonIN for delivering me a receiver ...,1
76982,'816327877415370752',Jan 3,AmazonHelp,85741735.0,2192504,11066,False,793,False,We answer Amazon support questions 7 days a we...,...,"@jemappellepatty Hi Patty, we can certainly lo...",0,False,jemappellepatty,8.163252e+17,1.506524e+07,0,False,"@jemappellepatty Hi Patty, we can certainly lo...",0

In [37]:
#checking the 'text_' column

datatext = data[['sum_count', 'text_']]

In [38]:
datatext

       sum_count                                              text_
77040          5  @amazon worst shopping  experience,  no servic...
74929          3  @ItsJosshA We always aim to deliver by the dat...
75021          2  @KStefl Sounds like you know what to add to yo...
76792          2  @thedexterouz Hi! We'd like to help. When you ...
75137          2  @Schoey1992 Happy Birthday, Matt! #FriendsFore...
...          ...                                                ...
75548          1  @QueenAttallah If you're waiting on an order, ...
75225          1  @AthenaRivera4 Feel better soon, Athena! We'd ...
76025          1  @AbhinavSaroj3 features and customer experienc...
76014          1  Thanks @amazonIN for delivering me a receiver ...
76982          0  @jemappellepatty Hi Patty, we can certainly lo...

[100 rows x 2 columns]

# Count the word frequency of the 100 tweets

In [39]:
def create_session():
  spk = SparkSession.builder \
      .appName("HW2") \
      .getOrCreate()
  return spk
spark = create_session()

import findspark
findspark.init()

In [40]:
ss = SparkContext.getOrCreate()

In [41]:
col_list =  list(datatext["text_"])
print(col_list)

['@amazon worst shopping  experience,  no service, no substantial reply to complaints, no delivery for 1 week post guarantee date.', '@ItsJosshA We always aim to deliver by the date given in your confirmation email. Have we missed that date? Any update in tracking?  ^NF', '@KStefl Sounds like you know what to add to your Halloween playlist for this year! ^BV', "@thedexterouz Hi! We'd like to help. When you have a moment, please connect with us here:  https://t.co/vlvfJr4nN9 ^YP", '@Schoey1992 Happy Birthday, Matt! #FriendsForever #FriendshipGoals ^JO', '@ratbones666 You so fancy!!! You already knooow!!! ^EP', "@ItsJosshA Oh no! I'm sorry! Please reach out to us so that we can look into options: https://t.co/hApLpMlfHN. ^JO", "@ThorpPerrow Awww! Happy Birthday, you don't look a day over 20 ;-) .Pass on your details here: https://t.co/g52MRb0AOt for lil surprise ^RS", "@bbyuniverseCB If the seller isn't able to help, you can see if you qualify for an A-to-z Guarantee claim here: https://t.co/nuYp2m187l. ^WJ", "@ProfGambs Hi- I'm sorry for the trouble! Please try these steps: https://t.co/EvQA8bgFIZ. I hope this helps! ^WJ", '@AlexisGraham99 Refunds to a credit card typically process within 3-5 business days. When was the refund requested? ^EN', '@mailstosandeep Hey, glad to know your issue has been resolved. Do keep us posted for any further concerns. ^CA', "@SharryPigTails I'm truly sorry. Typically, late packages arrive the following business day, please keep us posted. ^JA", '@Gerzinal Paw-some! The puppy that will be enjoying it is pretty cute! Thanks for sharing with us! ^JO', "@Adi_baddy Hey, thanks for flagging this up. We'll have it reviewed at the earliest. ^AK", "@EmmaWrafter I'm sorry to hear this. Please contact us so we may get this sorted: https://t.co/JzP7hlA23B. ^AE", '@eva____l Hey friendly customer! 🙋 Thanks for the shoutout, we love knowing that we helped.', '@aboutasix Sure, you can contact here  https://t.co/JzP7hlA23B ^AT', '@rwwishart You can leave your feedback about the experience here: https://t.co/SKgZKJCdNg ^AF', "@kindakuls We don't have access to your account through Twitter, but we can review the refund with you here: https://t.co/hApLpMlfHN^EN", "@rockerdharm Hi! We've received your details and shall be connecting with you soon. ^YP", "@pawansbaish Hi, request you to contact our kindle support team here : https://t.co/uWN5ABCIIf and we'll be happy to help. ^SH", '@pawansbaish Hey! Request you to contact our support teams using the link so that our Kindle teams can assist you further. ^HG', "@thblomme I can confirm that's an Amazon site. Feel free to reach back out if you have any questions. We're here to help! ^LI", '@Baileyoz Thanks for letting us know it arrived! Have a great evening. ^SJ', '@AbhinavSaroj3 Hi, I understand and will be sure to pass on your feedback to the concerned department for review. ^SO', "@ZeSaiyan We'll certainly try to get it to you, Danny. Has the tracking updated as out for delivery here: https://t.co/Y5jpI9gRhE? ^HB", "@AlyssaGoldman 1/2 I'm sorry you didn't receive your order. We ask that reviews are written about the quality and your experience w/an item.", "@Danadug I'm sorry for the trouble! Please contact us so we can look at the available options  for you: https://t.co/CYqkdUakWJ ^GL", '@PPramod2041984 Hi, apologies for the bad experience. Request you to return the incorrect item using the link provided above. ^SH', "@Elidan_8 Here's now to identify if the e-mail is from Amazon and how to report it if it's not: https://t.co/Zw0REzYrZU. ^CL", "@AmberMullennn I'm sorry it hasn't arrived. Here are some steps that can help: https://t.co/eGp7hBhsxY. ^RM", "@_dmarie99 That's not what we want to hear! When you contacted us regarding these issues, what information was provided to you? ^JA", '@joyfulneesh Thanks for the shout out! ^JO', "@brooklynnnross I'm sorry that the wrong case was sent! Was the item being fulfilled by Amazon or a third-party seller on our site? ^JO", '@U2Pride14 Thanks for your interest. You can visit https://t.co/SMLi9yxdAW for further details. Hope this helps! ^TM', "@Jae_Mulaa What's the expected delivery date and order status showing here: https://t.co/Y5jpI9gRhE? ^EN", '@SaifiFiroz Hey there, what is the error you getting while redeeming it? ^RW', '@__NaijaDrew Sorry for the delay. Did we indicate a new delivery date? Pls check e-mail for any order updates. ^SJ', '@magsophazjon Please contact us directly in the link below so we can have a further look into this: https://t.co/JzP7hlA23B ^PK', '@magsophazjon Hey you need to download the Amazon Video app which is separate to your shopping app. ^RS', '@bayou Glad we were able to ship your Fitbit to you so quickly! Let us know when it arrives! ^GL', "@jeedas Hi, at this time, we're unable to guarantee the availability of an MPOS device for card payment, for a COD order, as the 1/3 ^SH", "@mr__pandit We're delighted by your appreciation :) #StayHealthy #HappyNewYear :) ^SR", "@sydneycohenour Sorry, we can't access your account via Twitter. To view your tracking info, click here: https://t.co/Y5jpI9gRhE ^JA", '@AmazonHelp This is becoming a joke now. I need to speak to a supervisor. Your colleagues keep trying to put me through then cutting me off', "@plainbananas I'm sorry, but I don't have any further info on this. I recommend checking the website and social media for any updates. ^GL", "@SaifiFiroz Hi, that doesn't sound right. We'd like to look into this. Please report this to us, here: https://t.co/vlvfJr4nN9 ^SO", "@jtreadway33488 Please let us know if it doesn't arrive by end of day tomorrow. ^CL", "@AlyssaGoldman While you can't leave a product review, you can leave seller feedback about your experience here: https://t.co/HrsyfEIG2u ^AN", '@AlyssaGoldman 2/2 Was the shirt purchased from a Third-Party Seller? If so, have you contacted them: https://t.co/y3HHwiftLM? ^RA', '@AbhinavSaroj3 We encourage you to visit Amazon.in in your mobile browser where you will have access to our newest shopping(2/3)^SR', '@UOduckScotty If still eligible to modify the order you may edit the payment method for your orders here: https://t.co/Y5jpI9gRhE. ^AE', '@AbhinavSaroj3 Thank you for your interest in the Amazon App for Windows Phone. The application is no longer available for download(1/3)^SR', "@sgt_winters If you'd like, you can cancel the membership following the steps here: https://t.co/grr9TF1QwC. I hope this helps! ^SB", '@roxsi49 Hey, please contact here for support:  https://t.co/hApLpMlfHN ^AT', "@EumaeusOdyssey We're unable to see your acct.Typically, you can return kindle books select here for more info: https://t.co/vIHGDsPeUR. ^CO", "@EumaeusOdyssey Keep us posted on how it goes! We're here for you, Mark. ^HB", "@dragonflyeye (1/2) I'm sorry for any inconvenience this has caused. You can manage text alerts here: https://t.co/w7LfYcbaPb.", '@dragonflyeye (2/2) To manage app alerts, open the Settings menu in the Amazon app. ^KD', "@EumaeusOdyssey Let us know if you need anything else. We're here to help! ^AE", "@EumaeusOdyssey Thanks for letting us know it's been sorted out! Have a great night yourself 😊  ^SJ", "@gx_b57 I'm sorry to hear of this. Please give these steps a try: https://t.co/QYP5aSJV3e. If not found in 36hrs please let us know. ^TM", '@baba_Jabalpuri to create a replacement if the item is in stock with the same seller. Request you to place a new order for the 2/3 ^SH', '@ChadRAllen I will send on your feedback, but for now you can use Ctrl + F to help you find the address on a desktop :) ^CD', '@ronaldorlemes Is there a better way to start a new year? 😌 Happy reading! ^LG', "@baba_Jabalpuri item when its in stock and we'll make sure that this isn't repeated. 3/3 ^SH", "@baba_Jabalpuri Hi, we regret for the inconvenience. We'll work on your feedback and we'll make sure these instances never happen. ^SR", '@ghostfacezach Sorry the case is damaged! A return/replacement can be requested: https://t.co/nxGAAlzhis. Let us know if you need help.^EP', "@DurhamBelle I'm sorry, they don't have a direct number. You can contact us here for an update: https://t.co/5D5BOLXLjp. ^AR", '@Tamarastampone We aim to deliver by the est provided at checkout: https://t.co/36dGVsR8Ph If late, contact us: https://t.co/CYqkdUakWJ ^AF', '@LisaDeee You can do so here: https://t.co/TU1r2YUf3P. Let us know if you have any other questions! ^JO', '@KatmCor We should have return/exchange options here: https://t.co/HbTdZ01lMB. If not, pls phone/chat here: https://t.co/hApLpM3Ejd ^SJ', '@sEEntitties Thanks for bringing this to our attention. Do you have a link to this page so we can investigate the list please? ^HB', '@Chunkkyyy Is that the most recent scan on the tracking? How close is the location scan to you where it cleared customs? ^AN', "@tomroe93 Most carriers will deliver up until 8 PM. Please keep us posted if it doesn't arrive by then. ^WJ", "@AriannaDelBene Hi- Thanks so much for bringing this to our attention! I've had it reported. ^WJ", "@Chunkkyyy Couriers deliver until 21:00. If you order doesn't arrive by then please reach out to us here: https://t.co/JzP7hlA23B ^VS", "@baba_Jabalpuri Hi, apologies for the bad experience. We truly don't want our customers to experience this. We'll only be able 1/3 ^SH", "@DishaniSen1 Aw, we're so glad you're enjoying Prime Video. Our collection keeps getting better. Stay tuned and binge-watch for more! ^SO", "@DanJBalkwill I'm sorry for the frustrating experience w/your order. Please keep us posted on the replacement's delivery status! ^SJ", "@darshan_h_sheth \u200bHey, sorry to know you feel this way. We'd like to know what went wrong. Could you please elaborate the issue? ^AB", '@sj_booktweeter You can email via the link above and it will be forwarded to the relevant department. ^JJ', "@sj_booktweeter If you aren't seeing your review on the site, we'd advise contacting here: https://t.co/hApLpMlfHN ^CJ", '@LizzieeJones Please allow some time for a reply to your email - or feel free to contact us via Chat or Phone for real time assistance ^TD', '@JRC89 Our packaging team is always looking for feedback, John. Please submit the order details &amp; picture here: https://t.co/j5f0hsG7q6 ^HB', '@VickyFilmyDev Hi, the scan indicates that your shipment is in transit to your destination and should arrive by the EDD promised. ^SO', '@crashrider Hi Doug, you can arrange returns for most items online. See here for more info: https://t.co/ATNH0pOWqg ^CJ', "@_IzzyScott Sorry it arrived like this! If you'd like to return or exchange, you can do that here: https://t.co/ywRqdfK6Ba. ^AR", '@darshan_h_sheth Hey! Sorry about that. Have you filled in your details as asked earlier? So that we can assist you with this. ^MM', '@S_Tadesse Sorry for the trouble! Have you tried unlinking/linking Spotify through the Alexa app? ^CS', "@VlSlT Sorry to hear that, contact us here: https://t.co/hApLpMlfHN and we'll look into it for you. ^AS", '@darshan_h_sheth Hi! I get your concern. Kindly drop your details in the link shared earlier so that we can look into this and help you. ^HG', "@matt_linsley Please keep us posted on this and let us know if it doesn't arrive tomorrow. ^BV", "@heypardeep We're always looking to improve. Pls share your specific feedback via this form: https://t.co/z96J1aqgy4 ^SJ", "@QueenAttallah If you're waiting on an order, you can find tracking and delivery updates here: https://t.co/Y5jpI9gRhE. ^AR", "@AthenaRivera4 Feel better soon, Athena! We'd much rather be delivering fun things to you, rather than cold medicine. 😷😷 ^AM", '@AbhinavSaroj3 features and customer experience. Happy shopping on https://t.co/bXF5n7SXpf  (3/3)^SR', 'Thanks @amazonIN for delivering me a receiver that stopped working the very next day. https://t.co/tYqq1Ajrzk', '@jemappellepatty Hi Patty, we can certainly look into this with you. Please contact us here: https://t.co/hApLpMlfHN. ^AB']

In [42]:
a = ss.parallelize([col_list])

In [43]:
sp_df = a.flatMap(lambda line: line.split(" "))

In [44]:
wordcount = sp_df.map(lambda word: (word, 1)).reduceByKey(lambda a,b:a +b)

In [45]:
wordcount

PythonRDD[5] at RDD at PythonRDD.scala:53

In [46]:
def df_spark(spark,df,schema):
    df1 = spark.createDataFrame(df,schema)
    return df1

In [57]:
#col = ["Word", "Frequency"]
#spark_df = df_spark(spark,wordcount,col)

# Task 2

In [48]:
# read the file_text.csv file

In [49]:
df_task2 =spark.read.csv('C:/Users/amanka5/Desktop/find_text.csv',header=True)

In [50]:
df = spark.read.csv('C:/Users/amanka5/Desktop/Amazondata.csv',header=True)

In [51]:
df_task2.show(5)

+--------------------+----+
|              id_str|text|
+--------------------+----+
|'793270689780203520'|null|
|'793281386912354304'|null|
|'793299404975247360'|null|
|'793301295255945216'|null|
|'793315815411978240'|null|
+--------------------+----+
only showing top 5 rows

In [52]:
df.show(5)

+--------------------+--------------------+----------------+-----------+-------------------+---------------------+--------------+-----------------+--------------+--------------------+-------------+-------------+--------------------+------------------+--------------------+--------------+--------------------+--------------+---------+-----------------------+-------------------------+-----------------------+-------------+---------+--------------------+
|              id_str|    tweet_created_at|user_screen_name|user_id_str|user_statuses_count|user_favourites_count|user_protected|user_listed_count|user_following|    user_description|user_location|user_verified|user_followers_count|user_friends_count|     user_created_at|tweet_language|               text_|favorite_count|favorited|in_reply_to_screen_name|in_reply_to_status_id_str|in_reply_to_user_id_str|retweet_count|retweeted|                text|
+--------------------+--------------------+----------------+-----------+-------------------+---------------------+--------------+-----------------+--------------+--------------------+-------------+-------------+--------------------+------------------+--------------------+--------------+--------------------+--------------+---------+-----------------------+-------------------------+-----------------------+-------------+---------+--------------------+
|'793270689780203520'|Tue Nov 01 01:57:...|     SeanEPanjab|  143515471|              51287|                 4079|         False|               74|         False|Content marketer;...|   غریب الوطن|        False|                1503|               850|Thu May 13 17:43:...|            en|@AmazonHelp Can y...|             0|    False|             AmazonHelp|                     null|               85741735|            0|    False|                null|
|'793281386912354304'|Tue Nov 01 02:39:...|      AmazonHelp|   85741735|            2225450|                11366|         False|              796|         False|We answer Amazon ...|         null|         True|              149569|                53|Wed Oct 28 04:17:...|            en|@SeanEPanjab I'm ...|             0|    False|            SeanEPanjab|     7.932706897802035...|              143515471|            0|    False|                null|
|'793501578766319616'|Tue Nov 01 17:14:...|     SeanEPanjab|  143515471|              51287|                 4079|         False|               74|         False|Content marketer;...|   غریب الوطن|        False|                1503|               850|Thu May 13 17:43:...|            en|@AmazonHelp It wa...|             0|    False|             AmazonHelp|     7.932813869123543...|               85741735|            0|    False|@AmazonHelp It wa...|
|'793501657346682880'|Tue Nov 01 17:15:...|     SeanEPanjab|  143515471|              51287|                 4079|         False|               74|         False|Content marketer;...|   غریب الوطن|        False|                1503|               850|Thu May 13 17:43:...|            en|@AmazonHelp I am ...|             0|    False|             AmazonHelp|     7.932813869123543...|               85741735|            0|    False|                null|
|'793502854459879424'|Tue Nov 01 17:19:...|      AmazonHelp|   85741735|            2225450|                11366|         False|              796|         False|We answer Amazon ...|         null|         True|              149569|                53|Wed Oct 28 04:17:...|            en|@SeanEPanjab Plea...|             0|    False|            SeanEPanjab|     7.935015787663196...|              143515471|            0|    False|@SeanEPanjab Plea...|
+--------------------+--------------------+----------------+-----------+-------------------+---------------------+--------------+-----------------+--------------+--------------------+-------------+-------------+--------------------+------------------+--------------------+--------------+--------------------+--------------+---------+-----------------------+-------------------------+-----------------------+-------------+---------+--------------------+
only showing top 5 rows

In [53]:
d_final = df_task2.join(df,'id_str').select('id_str','text_')

In [54]:
d_final.show()

+--------------------+--------------------+
|              id_str|               text_|
+--------------------+--------------------+
|'793270689780203520'|@AmazonHelp Can y...|
|'793281386912354304'|@SeanEPanjab I'm ...|
|'793501578766319616'|@AmazonHelp It wa...|
|'793501657346682880'|@AmazonHelp I am ...|
|'793502854459879424'|@SeanEPanjab Plea...|
|'793504235400884224'|@SeanEPanjab With...|
|'793511847899070465'|@AmazonHelp It wa...|
|'793511899279208449'|@AmazonHelp if it...|
|'793513446633533440'|@SeanEPanjab I'm ...|
|'793299404975247360'|@JeffBezos @amazo...|
|'793301295255945216'|@aakashwangnoo Hi...|
|'793407430344310785'|@AmazonHelp How m...|
|'793423313674571776'|@aakashwangnoo Hi...|
|'793423314333134850'|@aakashwangnoo Pl...|
|'793467086869630977'|@AmazonHelp @amaz...|
|'793492430666498050'|@aakashwangnoo Hi...|
|'793535036213501952'|@AmazonHelp @amaz...|
|'793535221329113088'|@AmazonHelp @amaz...|
|'793537840533471232'|@AmazonHelp @amaz...|
|'793538125884645376'|@AmazonHelp @amaz...|
+--------------------+--------------------+
only showing top 20 rows

In [55]:
# Converting the final output to csv
d_final.toPandas().to_csv('C:/Users/amanka5/Desktop/final_output2.csv',index = False)